---
name: bluebuild
"on":
  schedule:
    - cron:
        "00 06 * * *"  # build at 06:00 UTC every day
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "website/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "website/**"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .
          config_file: .yamllint.yml
          strict: true


  bluebuild:
    name: Build Custom Image
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Custom Image
        id: build
        uses: blue-build/github-action@v1.8
        with:
          recipe: recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true

      - name: Fetch Image Digest
        id: get-digest
        if: github.event_name != 'pull_request'
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/wtgos:latest"
          DIGEST=$(skopeo inspect --creds="${{ github.actor }}:${{ github.token }}" docker://$IMAGE | jq -r '.Digest')
          if [ -z "$DIGEST" ] || [ "$DIGEST" == "null" ]; then
            echo "Failed to fetch digest for $IMAGE"
            exit 1
          fi
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Attest Build Provenance
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v2.2.0
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/wtgos
          subject-digest: ${{ steps.get-digest.outputs.digest }}
          push-to-registry: true
